### ISSUE TITLE
Error while using neuron detection

### ISSUE THREAD

**Issue by Lsayan** [DAMO-NLP-SG/multilingual_analysis#1]
I was running the code of neuron_detection.py but I got some error in line 35. The error is
ValueError: The following `model_kwargs` are not used by the model: ['candidate_premature_layers'] (note: typos in the generate arguments will also show up in this list).
Please look into this issue.

**Comment by zhaoyiran924** [comment]
May I know whether you change the transformer package correctly? This error occurs when the code does not use the transformer package that you changed for neuron detection.

**Comment by RadiantCrystal** [comment]
Hi @zhaoyiran924 , 

Very nice work! I am also getting the same issue. Can you please help me to import your local transformers package instead of directly installed 'transformers' package? When I am trying to import it from local folder it is showing the below error

`Traceback (most recent call last):
  File "/media/rimi/DATA/Rima/multilingual_analysis/neuron_detection/neuron_detection.py", line 17, in <module>
    from transformers import AutoModelForCausalLM, AutoTokenizer
ImportError: cannot import name 'AutoModelForCausalLM' from 'transformers' (unknown location)`

Can you please help me to fix this?

**Comment by Lsayan** [comment]
Can you please tell me exactly where in the transformer folder,in which file, I need to change in order to properly execute neuron_detection.py. I went through your instruction for the same but it was unclear for me. 
Thanks.

**Comment by zhaoyiran924** [comment]
As you can see from the code, there are two folders in the 'neuron_detection/transformers': 'models' and 'generations', just replacing the corresponding folder in your original transformer package will be fine.

**Comment by RadiantCrystal** [comment]
Hi @zhaoyiran924 ,

Yes, I got that but it is showing the below error.
`
Traceback (most recent call last): File "/media/rimi/DATA/Rima/multilingual_analysis/neuron_detection/neuron_detection.py", line 17, in <module> from transformers import AutoModelForCausalLM, AutoTokenizer ImportError: cannot import name 'AutoModelForCausalLM' from 'transformers' (unknown location)`

Can you please help me to fix this?

**Comment by zhaoyiran924** [comment]
May I know the model and transformer version you use? I use transformers==4.42.4

**Comment by RadiantCrystal** [comment]
Hi @zhaoyiran924 , I am currently using 4.47

**Comment by pratik443** [comment]
Hello @zhaoyiran924 can you please tell the versions of vllm and flash-atta for more clarity, unfortunately not able to get past the dependency lines of test_layers.py
