### ISSUE TITLE
Unable to import local transformers folder

### ISSUE THREAD

**Issue by RadiantCrystal** [DAMO-NLP-SG/multilingual_analysis#2]
Hi @zhaoyiran924 ,

Very nice work! I am also getting the same issue. Can you please help me to import your local transformers package instead of directly installed 'transformers' package? When I am trying to import it from local folder it is showing the below error

Traceback (most recent call last): File "/media/rimi/DATA/Rima/multilingual_analysis/neuron_detection/neuron_detection.py", line 17, in <module> from transformers import AutoModelForCausalLM, AutoTokenizer ImportError: cannot import name 'AutoModelForCausalLM' from 'transformers' (unknown location)

Can you please help me to fix this? Can you pass me the exact code for this?

**Comment by zhaoyiran924** [comment]
Thanks for your interest. As you can see from the code, there are two folders in the 'neuron_detection/transformers': 'models' and 'generations', just replacing the corresponding folder in your original transformer package will be fine.

**Comment by RadiantCrystal** [comment]
Hi @zhaoyiran924, Thanks for your response. Let me try this out once.

**Comment by RadiantCrystal** [comment]
@zhaoyiran924 , Unfortunately now this kind of issues are coming. 

`Traceback (most recent call last):
  File "/home/rimi/anaconda3/envs/SeaExam/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1793, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/home/rimi/anaconda3/envs/SeaExam/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rimi/anaconda3/envs/SeaExam/lib/python3.9/site-packages/transformers/generation/utils.py", line 27, in <module>
    from ..deepspeed import is_deepspeed_zero3_enabled
ModuleNotFoundError: No module named 'transformers.deepspeed'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rimi/anaconda3/envs/SeaExam/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1793, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/home/rimi/anaconda3/envs/SeaExam/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rimi/anaconda3/envs/SeaExam/lib/python3.9/site-packages/transformers/models/auto/modeling_auto.py", line 21, in <module>
    from .auto_factory import (
  File "/home/rimi/anaconda3/envs/SeaExam/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 40, in <module>
    from ...generation import GenerationMixin
  File "<frozen importlib._bootstrap>", line 1055, in _handle_fromlist
  File "/home/rimi/anaconda3/envs/SeaExam/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1781, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/home/rimi/anaconda3/envs/SeaExam/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1795, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.generation.utils because of the following error (look up to see its traceback):
No module named 'transformers.deepspeed'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/media/rimi/DATA/Rima/multilingual_analysis/neuron_detection/neuron_detection.py", line 17, in <module>
    from transformers import AutoModelForCausalLM, AutoTokenizer
  File "<frozen importlib._bootstrap>", line 1055, in _handle_fromlist
  File "/home/rimi/anaconda3/envs/SeaExam/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1782, in __getattr__
    value = getattr(module, name)
  File "/home/rimi/anaconda3/envs/SeaExam/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1781, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/home/rimi/anaconda3/envs/SeaExam/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1795, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.auto.modeling_auto because of the following error (look up to see its traceback):
Failed to import transformers.generation.utils because of the following error (look up to see its traceback):
No module named 'transformers.deepspeed'`

**Comment by zhaoyiran924** [comment]
sry, seems the bug is  "No module named 'transformers.deepspeed'"? But I do not use transformers.deepspeed, so I did not encounter that bug. I don't know what will change if implemented on deepspeed.

**Comment by RadiantCrystal** [comment]
Hi @zhaoyiran924 , I have managed to fix the transformers issue. Although I am now getting a new issue. Could you please help me to fix it? Which part of the code I have to modify?

![image](https://github.com/user-attachments/assets/dc3774f9-63cf-4485-a9c4-45d17645a172)

**Comment by zhaoyiran924** [comment]
Could you comment the try: and except to check where does the bug come from?

**Comment by RadiantCrystal** [comment]
Also @zhaoyiran924 , After execution of code python neuron_detection.py english 1000 , I am getting this error.

![image](https://github.com/user-attachments/assets/4336ebc5-1d20-4c88-94b1-bf8231c64b8f)

**Comment by RadiantCrystal** [comment]
> Could you comment the try: and except to check where does the bug come from?

Could you please tell me which line of the code file neuron_detection.py you are referring to? @zhaoyiran924

**Comment by zhaoyiran924** [comment]
Oh, yes, because the code has bugs, so no neurons are detected. Could you comment the try: and except: to check where is the bug?

**Comment by zhaoyiran924** [comment]
https://github.com/DAMO-NLP-SG/multilingual_analysis/blob/main/neuron_detection/neuron_detection.py#L73

**Comment by RadiantCrystal** [comment]
> https://github.com/DAMO-NLP-SG/multilingual_analysis/blob/main/neuron_detection/neuron_detection.py#L73

@zhaoyiran924 , Yes. removed try-except. Now this error is coming. Can you please tell me at which line of each code file I need to change what if you consider llama3 as the chosen model?

![image](https://github.com/user-attachments/assets/4058fae3-d428-4478-a955-d7f83269b214)

**Comment by zhaoyiran924** [comment]
Seems like this line fails to work? https://github.com/DAMO-NLP-SG/multilingual_analysis/blob/main/neuron_detection/transformers/generation/utils.py#L2256
As the early_exit_layers is None now.

**Comment by RadiantCrystal** [comment]
> Seems like this line fails to work? https://github.com/DAMO-NLP-SG/multilingual_analysis/blob/main/neuron_detection/transformers/generation/utils.py#L2256 As the early_exit_layers is None now.

Can you please tell me exactly where I need to set it in the utils.py? In the neuron_detection.py file, candidate_premature_layers is already set. @zhaoyiran924

**Comment by zhaoyiran924** [comment]
Oh, I think it's because you do not use greedy_search when generating, you need to set the generation_config as greedy decoding. For example, for llama3, you can set as this:

{
"bos_token_id": 128000,
"eos_token_id": 128001,
"transformers_version": "4.40.0.dev0"
}

Or you can set in the model.generate() function here https://github.com/DAMO-NLP-SG/multilingual_analysis/blob/main/neuron_detection/neuron_detection.py#L35,

Sorry I forgot to mention this in the readme

**Comment by RadiantCrystal** [comment]
> Oh, I think it's because you do not use greedy_search when generating, you need to set the generation_config as greedy decoding. For example, for llama3, you can set as this:
> 
> { "bos_token_id": 128000, "eos_token_id": 128001, "transformers_version": "4.40.0.dev0" }
> 
> Or you can set in the model.generate() function here https://github.com/DAMO-NLP-SG/multilingual_analysis/blob/main/neuron_detection/neuron_detection.py#L35,
> 
> Sorry I forgot to mention this in the readme

Hi @zhaoyiran924 , sorry for asking too many questions. Thanks for continuously answering my queries.

I tried this workaround just now but unfortunately same error is coming up. 

Added like this -->

activate_keys_v, activate_keys_o, layer_keys = model.generate(**{'input_ids':inputs.input_ids, 'max_new_tokens':1, 'candidate_premature_layers':candidate_premature_layers,
"bos_token_id": 128000,
"eos_token_id": 128001
})

**Comment by zhaoyiran924** [comment]
I think maybe you can set a breakpoint at https://github.com/DAMO-NLP-SG/multilingual_analysis/blob/main/neuron_detection/transformers/generation/utils.py#L2254 to check whether it really uses greedy_search() function and whether early_exit_layers is really set a valid list?

**Comment by zhaoyiran924** [comment]
Oh, 

{
"bos_token_id": 128000,
"eos_token_id": 128001,
"transformers_version": "4.40.0.dev0"
}

is set in the model's 'generataion_config.json'

**Comment by RadiantCrystal** [comment]
> Oh,
> 
> { "bos_token_id": 128000, "eos_token_id": 128001, "transformers_version": "4.40.0.dev0" }
> 
> is set in the model's 'generataion_config.json'

Hi @zhaoyiran924 , it is already set in model's generation_config.json file.

**Comment by RadiantCrystal** [comment]
> I think maybe you can set a breakpoint at https://github.com/DAMO-NLP-SG/multilingual_analysis/blob/main/neuron_detection/transformers/generation/utils.py#L2254 to check whether it really uses greedy_search() function and whether early_exit_layers is really set a valid list?

Hi @zhaoyiran924, I just now checked this, but it is not going inside greedy_search() function.

**Comment by RadiantCrystal** [comment]
Hi @zhaoyiran924 , Now I am getting new issue. Can you please help me to fix it?
![image](https://github.com/user-attachments/assets/c4822dfa-f1f9-4864-aaaa-46f2f5a8ec7f)

**Comment by RadiantCrystal** [comment]
Hi @zhaoyiran924 , can you please help me out to resolve previous issue?

**Comment by xiaoyaoyou9** [comment]
> @zhaoyiran924 , Unfortunately now this kind of issues are coming.
> 
> `Traceback (most recent call last): File "/home/rimi/anaconda3/envs/SeaExam/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1793, in _get_module return importlib.import_module("." + module_name, self.**name**) File "/home/rimi/anaconda3/envs/SeaExam/lib/python3.9/importlib/**init**.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "", line 1030, in _gcd_import File "", line 1007, in _find_and_load File "", line 986, in _find_and_load_unlocked File "", line 680, in _load_unlocked File "", line 850, in exec_module File "", line 228, in _call_with_frames_removed File "/home/rimi/anaconda3/envs/SeaExam/lib/python3.9/site-packages/transformers/generation/utils.py", line 27, in from ..deepspeed import is_deepspeed_zero3_enabled ModuleNotFoundError: No module named 'transformers.deepspeed'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "/home/rimi/anaconda3/envs/SeaExam/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1793, in _get_module return importlib.import_module("." + module_name, self.**name**) File "/home/rimi/anaconda3/envs/SeaExam/lib/python3.9/importlib/**init**.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "", line 1030, in _gcd_import File "", line 1007, in _find_and_load File "", line 986, in _find_and_load_unlocked File "", line 680, in _load_unlocked File "", line 850, in exec_module File "", line 228, in _call_with_frames_removed File "/home/rimi/anaconda3/envs/SeaExam/lib/python3.9/site-packages/transformers/models/auto/modeling_auto.py", line 21, in from .auto_factory import ( File "/home/rimi/anaconda3/envs/SeaExam/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 40, in from ...generation import GenerationMixin File "", line 1055, in _handle_fromlist File "/home/rimi/anaconda3/envs/SeaExam/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1781, in **getattr** module = self._get_module(self._class_to_module[name]) File "/home/rimi/anaconda3/envs/SeaExam/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1795, in _get_module raise RuntimeError( RuntimeError: Failed to import transformers.generation.utils because of the following error (look up to see its traceback): No module named 'transformers.deepspeed'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "/media/rimi/DATA/Rima/multilingual_analysis/neuron_detection/neuron_detection.py", line 17, in from transformers import AutoModelForCausalLM, AutoTokenizer File "", line 1055, in _handle_fromlist File "/home/rimi/anaconda3/envs/SeaExam/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1782, in **getattr** value = getattr(module, name) File "/home/rimi/anaconda3/envs/SeaExam/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1781, in **getattr** module = self._get_module(self._class_to_module[name]) File "/home/rimi/anaconda3/envs/SeaExam/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1795, in _get_module raise RuntimeError( RuntimeError: Failed to import transformers.models.auto.modeling_auto because of the following error (look up to see its traceback): Failed to import transformers.generation.utils because of the following error (look up to see its traceback): No module named 'transformers.deepspeed'`

I also meet this problem! I find this error in utils.py belongs to the generation folder. But the transformers package doesn't have deepspeed folder. How do you overcome it! Thank you! And if you find how to implement this project, we can discuss about it. I need your help! Thank you!

**Comment by Lsayan** [comment]
Hi @xiaoyaoyou9, actually we are also getting similar issue while running that file.
I was encountering an error that was originating from utils.py file present in the generation folder in Transformer.
![image](https://github.com/user-attachments/assets/4161481a-0c50-4b2d-ab28-c377fdbadc8d)

This function is present within the greedy_search function.
Can you please help me resolve this issue? I was not able to understand which function is being invoked using self() call. Thanks for the help.

**Comment by pratik443** [comment]
> Hi [@zhaoyiran924](https://github.com/zhaoyiran924) , I have managed to fix the transformers issue. Although I am now getting a new issue. Could you please help me to fix it? Which part of the code I have to modify?
> 
> ![image](https://github.com/user-attachments/assets/dc3774f9-63cf-4485-a9c4-45d17645a172)

Hello, How did you fix the transformers issue, I'm also getting all kind of transformers issues

**Comment by pratik443** [comment]
Hello @everyone, if you are still wondering how to run the code, I was able to replicate the code. below are the versions of packages used and few instructions.

transformers==4.42.4
vllm==0.5.3
cupy-cuda12x
datasets==2.20.0


also as the authors mentioned in different chats to complete replace the transformers subfolders like generations and models, but rather than that, just replace the file names that you can find in you environment packages, rather than replacing the whole folder with the transformers found in GitHub just replace the files

**Comment by Zongmin741** [comment]
@pratik443 
Hello, thank you for the advice. I completely followed your instructions but still got errors:

![Image](https://github.com/user-attachments/assets/a7a42745-2af7-4c91-b779-2858da6b08c4)

Do you know how to debug?

**Comment by pratik443** [comment]
> [@pratik443](https://github.com/pratik443) Hello, thank you for the advice. I completely followed your instructions but still got errors:
> 
> ![Image](https://github.com/user-attachments/assets/a7a42745-2af7-4c91-b779-2858da6b08c4)
> 
> Do you know how to debug?

Hello @Zongmin741 , It happens generally because output_hidden_states is default set to false, in your CausalLM class of any model you are using, in modelling_{model).py just force set 'output_hidden_states = True' in forward function

**Comment by junzhaixing** [comment]
> [@pratik443](https://github.com/pratik443) Hello, thank you for the advice. I completely followed your instructions but still got errors:
> 
> ![Image](https://github.com/user-attachments/assets/a7a42745-2af7-4c91-b779-2858da6b08c4)
> 
> Do you know how to debug?

@Zongmin741,

I think the main issue is that the model is not running in **greedy decoding** mode.  
You can fix this by modifying the generation function as follows:

```python
hidden_states, outputs, activate_keys_fwd_up, activate_keys_fwd_down, activate_keys_q, activate_keys_k, activate_keys_v, activate_keys_o, layer_keys = model.generate(
    **{
        'input_ids': inputs.input_ids,
        'max_new_tokens': 1,
        'candidate_premature_layers': candidate_premature_layers,
        'do_sample': False,
        'num_beams': 1
    }
)

**Comment by Zongmin741** [comment]
> > [@pratik443](https://github.com/pratik443) Hello, thank you for the advice. I completely followed your instructions but still got errors:
> > ![Image](https://github.com/user-attachments/assets/a7a42745-2af7-4c91-b779-2858da6b08c4)
> > Do you know how to debug?
> 
> [@Zongmin741](https://github.com/Zongmin741),
> 
> I think the main issue is that the model is not running in **greedy decoding** mode. You can fix this by modifying the generation function as follows:
> 
> hidden_states, outputs, activate_keys_fwd_up, activate_keys_fwd_down, activate_keys_q, activate_keys_k, activate_keys_v, activate_keys_o, layer_keys = model.generate(
>     **{
>         'input_ids': inputs.input_ids,
>         'max_new_tokens': 1,
>         'candidate_premature_layers': candidate_premature_layers,
>         'do_sample': False,
>         'num_beams': 1
>     }
> )

Many thanks! It works.
